### ISSUE TITLE
Feature: Users can browse a searchable catalog

### ISSUE THREAD

**Issue by chris-marron** [chris-marron/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can browse a searchable catalog that displays images, descriptions, and prices of each item for sale.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

the user will be able to see a catalog of items that they'll be able to interact with

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="324" alt="CleanShot 2023-02-20 at 11 45 32@2x" src="https://user-images.githubusercontent.com/79817237/220187842-949c9e9b-77f5-4f69-931b-aeab003cc8f6.png">

![CleanShot 2023-02-20 at 12 03 21@2x](https://user-images.githubusercontent.com/79817237/220190322-9e40f4e6-cbf5-4d27-9eea-fb105358d48f.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to have a category table, cart table, product table, cart item table, and order item table, and possibly add a user and order table if enough time.
- [x] Update `data.sql` to be able to store items that have been added to the cart 

### ☁️ Server Tasks

- [x] Update `server/index.js` to set up a server to handle incoming requests and send out responses from the client side.
- [x] write a request to the API in order to display said products in the catalog
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to display a nav bar 
- [x] Create a component to display a catalog of items by mapping them
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
